### ISSUE TITLE
How to represent sequences (vs grids)?

### ISSUE THREAD

**Issue by neothemachine** [neothemachine/coveragejson#1]
Currently a trajectory is defined like

```js
{
  "type": "Trajectory",
  "sequence": [
    ["2008-01-01T04:00:00Z", 1, 20],
    ["2008-01-01T04:30:00Z", 2, 22]
   ],
  "z": 5
}
```

However, this representation is less efficient as bigger few typed arrays cannot be used (within CBOR). And also it is not obvious how coordinate bounds should be defined.

An alternative representation is:

```js
{
  "type": "Trajectory",
  "x": [1,2],
  "y": [20,22],
  "t" : ["2008-01-01T04:00:00Z", "2008-01-01T04:30:00Z"],
  "z": 5,
  "sequence": ["x","y","t"]
}
```

Here bounds can be easily defined like `"xBounds": [0.5,1.5,2.5]`. The disadvantage is that the formal definition of the coordinate space gets more complicated and that one has to look at the `sequence` value to see which members shall be interpreted as grid or sequence.

Any ideas?

**Comment by jonblower** [comment]
Good idea, I like it. I think the pros far outweigh the cons. I can't see that the definition of the coordinate space is more complicated - what do you mean here?

Does this mean that we should also have:

`"grid": ["x", "y", "t"]`

for other coverages, where the coordinates should be interpreted as the orthogonal axes of a grid?

**Comment by neothemachine** [comment]
> Good idea, I like it. I think the pros far outweigh the cons. I can't 
> see that the definition of the coordinate space is more complicated - 
> what do you mean here?
>
Currently the coordinate space is defined as an array where each element 
is an array of coordinates. So for grids this is easy, just [t,z,y,x] or 
similar. For sequence-type domains this is currently [sequence] or [t, 
sequence] or similar, meaning that each coordinate array in a sequence 
represents one coordinate in the coordinate space, along that axis, a 
"sequence axis". So, if you remove the "sequence" field, you have to 
recreate this structure for the formal definition of the space. As this 
is a formal thing that has to be done only once for the spec I agree 
that this should not count as a con.

> Does this mean that we should also have:
>
> |"grid": ["x", "y", "t"]|
>
> for other coverages, where the coordinates should be interpreted as 
> the orthogonal axes of a grid?
>
Possibly, or you say that this is the default, which may make sense as 
grid axes will be quite common in several domain types.

**Comment by jonblower** [comment]
Do we need to explicitly specify:

`"grid": ["x", "y", "t"]`

in order to establish axis ordering in the rangeset? (I'm assuming that in JSON documents the order of properties does not matter much, if at all, so perhaps we need to specify it explicitly.)

**Comment by neothemachine** [comment]
Well, as you can have a mix of grid-type coordinates and sequence-type (see Section) a single `"grid"` would not be enough. And I also don't want to bloat the document with that. Currently the order is defined in the spec for each domain type.

**Comment by neothemachine** [comment]
Integrated in spec for Trajectory and Section. Please reopen if there are any further problems with that.
