### ISSUE TITLE
Discrete vs continuous parameters & Categories encoding

### ISSUE THREAD

**Issue by neothemachine** [neothemachine/coveragejson#12]
I read a bit on the levels of measurement topic. I think we can say that if a unit is defined in the Parameter, then it is definitely continuous (=interval or ratio scale). So, I would say we do a similar thing by saying, if categories are defined (format tbd) then it is definitely discrete (=nominal scale) and unit and categories cannot be defined simultaneously. There's also the ordinal scale which is terms with an ordering relation (e.g. school grades), but I think we can ignore that for now. I'm not yet sure how the "quantity" plays into that, and whether it is possible to derive from the unit if the interval (°C) or ratio (K) scale applies and whether this is encoded in existing unit vocabularies/data sets.

For encoding categories (in a Parameter) we should enforce numbers as keys (for efficiency) and strings as values/labels. Since JSON cannot have numbers as keys, we have to work-around that a bit (which may be better for LD anyway). Maybe something like:
```js
"categories": [
  {
    "id": "http://.../landcover1/categories/grass",
    "value": 1,
    "label": "Grass",
    "description": "Very green grass."
  }, ...
]
```

**Comment by neothemachine** [comment]
Or rather... if it has a categories member, then it's discrete, otherwise continuous. That's a bit easier for clients to check.

**Comment by jonblower** [comment]
Yes - also, some quantities (e.g. salinity) might not have units but still be continuous. I think it's fine to ignore the "ordinal/interval/ratio" distinction for now. (And I'm not even sure what salinity is - a rare example of a real-valued ordinal scale maybe??)
