### ISSUE TITLE
How much LD is too much?

### ISSUE THREAD

**Issue by neothemachine** [neothemachine/coveragejson#4]
Currently we try to use JSON-LD in some way to provide as much linked data associations as possible. However this is becoming difficult in some ways.

From a JSON / client point of view you want to have easy access to the (meta)data in a CoverageJSON document. One reoccuring example causing trouble is how to expose parameters and ranges.

Ideally, you want something like:
```js
	"parameters": {
		"TMP": {
			"type": "Parameter",
			"id": "http://.../data/mydataset/params/TMP",
			"description": "...",
			"observedProperty": {
				"id": "http://.../sea_water_potential_temperature",
				"label": "Sea Water Potential Temperature",
				"description": "Something lengthy here"
			},
			"unit": {
				"id": "http://qudt.org/kelvin",
				"label": "Kelvin",
				"symbol": "K"
			}
		},{
			// ...
		}
	},
	"ranges": {
		"TMP": {
			"id": "http://.../data/mydataset/cov1/range/TMP",
			"values": [1,2,3,...]
		}
	}
```

So you want some local key by which to reference a certain parameter and its range:
```js
var unit = cov.parameters.TMP.unit.symbol
var vals = cov.ranges.TMP.values
```

This however doesn't make much sense in JSON-LD/RDF triples as it would lead to something like
```
<Coverage1> <parameterSet> <ParamSet1>
<ParamSet1> <parameter> <TMP>
<TMP> is a <Parameter>
<TMP> <unit> <http://qudt.org/kelvin>
<http://qudt.org/kelvin> <symbol> "K"
<Coverage1> <rangeSet> <RangeSetCov1>
<RangeSetCov1> <TMP> <http://.../data/mydataset/cov1/range/TMP>
```
The problem is that `<TMP>` becomes a global ID even though it is just a local identifier which should not be exposed as LD. "ranges" should probably not be exposed as LD anyway.

The alternative is the currently used approach in the spec:
```js
	"parameters": [
		 {
			"type": "Parameter",
			"id": "http://.../data/mydataset/params/TMP",
			"description": "...",
			"observedProperty": {
				"id": "http://.../sea_water_potential_temperature",
				"label": "Sea Water Potential Temperature",
				"description": "Something lengthy here"
			},
			"unit": {
				"id": "http://qudt.org/kelvin",
				"label": "Kelvin",
				"symbol": "K"
			}
		},{
			// ...
		}
	],
	"ranges": {
		"http://.../data/mydataset/params/TMP": {
			"id": "http://.../data/mydataset/cov1/range/TMP",
			"values": [1,2,3,...]
		}
	}
```
This would become something like:
```
<Coverage1> <parameter> <http://.../data/mydataset/params/TMP>
<http://.../data/mydataset/params/TMP> is a <Parameter>
<http://.../data/mydataset/params/TMP> <unit> <http://qudt.org/kelvin>
<http://qudt.org/kelvin> <symbol> "K"
<Coverage1> <rangeSet> <RangeSetCov1>
<RangeSetCov1> <http://.../data/mydataset/params/TMP> <http://.../data/mydataset/cov1/range/TMP>
```

Here the modelling makes more sense and even the range set makes sense (analogous to w3c data cube ontology). But as we don't want to expose the ranges anyway we can ignore that. The disadvantage is that we don't have local keys anymore and the parameters are now a list whereas the ranges is still a map which may be hard to understand. Accessing data would look like:
```js
var paramId = "http://.../data/mydataset/params/TMP"
var unit = cov.parameters.find(p => p == paramId).unit.symbol
var vals = cov.ranges[paramId].values
```
which means you have to deal with URIs to get your data which from an LD point may be fine but for common usage, even with some shelll scripting to quickly plot a range of a coverage, it may be annoying.

Ultimately the issue is that JSON-LD's context mechanism doesn't provide enough flexibility to model structures as in the first example and still get RDF triples as in the second example. There is a library called [JSON-LD Macros](https://github.com/antoniogarrote/json-ld-macros) which would allow for such more complex transformations, however this is not supported in any way by JSON-LD processors currently and the macro definitions are currently not defined as part of the JSON-LD document but only when using the library.

We have multiple options:
1. Ignore LD for such cases, use the most convenient JSON structure, and hope that JSON-LD Macros become part of JSON-LD 2 so that we can fix the relevant semantic parts.
2. Use the slightly inconvenient JSON-LD structure without local keys to make LD people happy.
3. ...?

It should be considered to which level CoverageJSON contains LD context and what the goals of CoverageJSON are.

**Comment by jonblower** [comment]
I see. How about we define both `params` and `ranges` to be arrays of objects? I think defining one as an array and the other as a map is counter-intuitive, even though there's a decent reason for it.

Then each Param or Range object could have an `id` (which is a URL) and a `shortName` (a short string that is unique within the dataset). The purpose of the `shortName` (or whatever it could be called) is just for convenience in APIs.

(We could have a convention that the last part of the `id` URL is used as the `shortName` if none is provided, or perhaps the short name could be auto-generated.)

So a Python/Javascript API could parse the document and provide a `getParamByShortName()` method, or perhaps create a map, enabling usage like `cov.ranges[shortName]`.

I know this means that an API would have to do some extra work over and above standard JSON deserialization, but any API would probably do some internal validation of the JSON anyway, and the internal map could be created as part of this process.

**Comment by neothemachine** [comment]
> I see. How about we define both |params| and |ranges| to be arrays of 
> objects? I think defining one as an array and the other as a map is 
> counter-intuitive, even though there's a decent reason for it.
>
The nice thing about ranges being a map is that you encode a constraint 
into the data structure, namely that there can only be one range per 
parameter. With an array you loose that. And the way parameters are 
currently defined you might easily think that they can be reused and 
that you would identify two ranges of the same parameter by the range id 
or so.

**Comment by jonblower** [comment]
Could you have:
```js
{
   "parameters": [
         {
            "type": "Parameter",
            "id": "http://.../data/mydataset/params/TMP",
            "shortName": "TMP",
            ...
         }
    ],

    "ranges" : {
         "TMP": {
             // range object
         }
    }
}
```

With a @context defining that `"TMP"` maps to `"http://.../data/mydataset/params/TMP"`?

In that way, linked data clients are able to interpret `"TMP"` as a global URL that points to the parameter object, but "normal" clients can just use the `shortName` as the key.

**Comment by neothemachine** [comment]
I was thinking the same and actually this is rather easy as I just found out you can have [multiple context definitions](http://www.w3.org/TR/json-ld/#advanced-context-usage) where later ones override previous ones (but there should be no need for overriding)! 

That means, we can do:

```js
{
  "@context": [
     "http://covjson/basecontext.jsonld",
     {
       "TMP" : "http://../mydataset/TMP"
     }
   ],
   "parameters": [
         {
            "type": "Parameter",
            "id": "http://.../data/mydataset/params/TMP",
            "shortName": "TMP",
            ...
         }
    ],
    "ranges" : {
         "TMP": {
             // range object
         }
    }
}
```

I think that's as good as it gets currently.

**Comment by neothemachine** [comment]
I would also explicitly say that "shortName" must **not** be an LD predicate.

**Comment by jonblower** [comment]
Yes, makes sense.

**Comment by neothemachine** [comment]
Although, do we still need "shortName" then? We could also just use:

```
{
  "@context": [
     "http://covjson/basecontext.jsonld",
     {
       "TMP" : "http://../mydataset/parameters/TMP"
     }
   ],
   "parameters": [
         {
            "type": "Parameter",
            "id": "TMP",
            ...
         }
    ],
    "ranges" : {
         "TMP": {
             // range object
         }
    }
}
```

**Comment by jonblower** [comment]
Oh yeah, that works.

**Comment by neothemachine** [comment]
I just made an [extremely interesting discovery](http://www.w3.org/TR/json-ld/#data-indexing) in the JSON-LD spec: Data Indexing! This is exactly what we need here for the parameters.

You define parameters in the context as:
```js
"parameters": {
       "@id": "covjson:parameter",
       "@container": "@index"
}
```
and then you can use whatever non-IRI keys you want instead of having a list!
```js
    "parameters": {
        "TMP": {
            "type": "Parameter",
            "id": "http://.../data/mydataset/params/TMP",
            "description": "...",
        },
        "WIND": {
            "type": "Parameter",
            "id": "http://.../data/mydataset/params/WIND",
            "description": "...",
        }
    },
```

Wonderful!

**Comment by neothemachine** [comment]
The question now is how this fits with the `ranges` field, because for that we currently have IRIs as predicate like `<coverage1> <http://.../params/TMP> <range1>`. And if we maintain that it would mean we have to require that the `id` field in each parameter must be equal to its parent key and also still be included in the context as described earlier. Given the new findings I'm in favour of modelling it differently to make it more simple. As in `<coverage1> <range> <range1>` and then `<range1> <parameter> <http://.../params/TMP>` which would be quite standard I think, although not like data cube anymore.

**Comment by neothemachine** [comment]
(Note for earlier approach: An ID in JSON-LD must always be the full name and cannot be aliased within the context! that means we would still have to use shortName)

Hm, I may have cheered too early. With the `@index` modelling we now have the problem that when using a JSON-LD client you don't know which range to load (if the ranges are URLs only) for a given parameter, as the index keys disappear. That was quite nice before, but then you had the context overhead. Another problem is that a range object itself now would get a `parameter` field with URI to make the connection within LD complete again. And this doesn't make much sense when you have a standalone CoverageJSON Range document, so it would need to be optional in general and required within a Coverage document.

It may be good (not perfect...) to combine both approaches, so having ranges as data-cube and parameters as index. So the ranges are like before and the param IDs still need to be aliased to be used as keys in the rangeSet object.
```js
{
  "@context": [
     {
       "id": "@id", "type": "@type",
       "parameters": { "@id": "covjson:parameter", "@type": "@id", "@container": "@index" },
       "Parameter": "covjson:Parameter",
       "ranges": { "@id": "covjson:rangeSet" },
       "TMP" : {"@id": "http://must/be/uri/if/given", "@type": "@id"}
     }
   ],
  "id": "http://mycov1",
   "parameters": {
       "TMP": {
         "type": "covjson:Parameter",
         "id": "http://must/be/uri/if/given"
       }
   },
    "ranges" : {
      "TMP": "http://range1"
    }
}
```
I think that may just be acceptable.

**Comment by neothemachine** [comment]
I incorporated the combined approach to the spec.
