### ISSUE TITLE
Which types of polygons do we need?

### ISSUE THREAD

**Issue by neothemachine** [neothemachine/coveragejson#7]
Currently the spec supports domains that can have a single GeoJSON polygon (one exterior and optionally multiple interior rings/holes). The question is: Is that too general, too restricted, or just right?

I can think of a coverage which may have a country as polygon and for some countries you would need GeoJSON's MultiPolygon. So, e.g. total population of Portugal for each year over the last 50 years, which would be a MultiPolygonSeries. I guess the question is whether such coverages are a use case of CoverageJSON. Having the full outlines of a country may not have any benefit, especially if the outlines change over the years. Typical governmental datasets would just use an ID for identifying the country.

**Comment by jonblower** [comment]
I think it's OK for now to use single polygons, and I would be surprised if we need interior rings/holes. I think the main use case is for data that have been aggregated to the level of an administrative area or land use parcel (maybe a country, more likely a smaller region). I suggest that we keep the possibility of a MultiPolygonSeries in our minds, but don't implement it unless we find we need it.

**Comment by neothemachine** [comment]
Ok, one thing to keep in mind also is that MultiPolygonSeries may be interpreted as two things, either a single MultiPolygon with one coordinate in coordinate space, or multiple Polygons each with a coordinate in coordinate space. If you want to support both you need different names to separate them. Is the latter useful for us now? E.g. a coverage which has the percentages of different land cover categories for a number of land use parcels.

**Comment by jonblower** [comment]
> E.g. a coverage which has the percentages of different land cover categories for a number of land use parcels.

Yes, I think we need this, and this is more useful than the other sort of "MultiPolygon" you mention.
