### ISSUE TITLE
How to model polygon-type domains?

### ISSUE THREAD

**Issue by neothemachine** [neothemachine/coveragejson#8]
This is related to #7 and specifically about how to serialize the polygon-type domains we need and also what restrictions these should have.

Currently, a polygon cannot have z-coordinates at its vertices. And also currently polygons are defined in a single field with the same structure as GeoJSON polygons (supporting holes):

```js
"polygon": [ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ] ]
```
for the Polygon(Series) domain, and
```js
"polygon": [
    [ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ] ],
    [ [ [200.0, 10.0], [201.0, 10.0], [201.0, 11.0], [200.0, 11.0], [200.0, 10.0] ] ]
  ]
```
for the MultiPolygon(Series) domain.

Questions are:
- Should polygons be allowed to have z-coordinates at each vertex?
- Should polygons be serialized in single-field GeoJSON format? If not, what are alternatives? Pros/cons

**Comment by jonblower** [comment]
I don't think we need z coordinates at each vertex. I don't quite understand the second bullet. Do you mean using a GeoJSON Geometry object instead of an array of vertices? Can you post what that might look like?

**Comment by neothemachine** [comment]
With the second bullet I mean exactly the first example I gave. If you skip hole support, you could have an equivalent form like:
```js
"x": [100.0, 101.0, 101.0, 100.0, 100.0],
"y": [0.0, 0.0, 1.0, 1.0, 0.0],
"polygon": ["x","y"]
```
but I don't like that because it's not obvious how it scales for the MultiPolygon domain case (the second example in the first post).

**Comment by jonblower** [comment]
Right - I don't like that form either. I think the syntax

```js
"polygon": [
    [ [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ] ],
    [ [ [200.0, 10.0], [201.0, 10.0], [201.0, 11.0], [200.0, 11.0], [200.0, 10.0] ] ]
  ]
}
```
is best.

**Comment by neothemachine** [comment]
Ok, done.
